/**
 **************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 **************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 **************************
 */
#include <stdio.h>
#include <ctype.h>
#include <string.h>
#include "Lib.h"
#include "stm32f091xx_USART.h"
#include "cbfifo.h"
#include "wave.h"
 #define MAX_COMMAND_LEN 128
//extern int32_t fp_sin(int32_t x);

int sin_frequency=0;
int square_frequency=0;
int duty_cycle=0;
uint8_t DMA_FLAG=0;

// Command processor loop
void command_processor() {
    char BufferCommand[MAX_COMMAND_LEN];
    size_t CommandLength = 0;

    printf("$$ ");
    fflush(stdout);

    while (1) {
        char ch;
        if (cbfifo_rx_dequeue(&ch, 1)) {
            if (ch == '\b' || ch == 127) {
                if (CommandLength > 0) {
                    CommandLength--;
                    printf("\b \b");
                }
            } else if (ch == '\r' || ch == '\n') {
                printf("\r\n");
                fflush(stdout);

                BufferCommand[CommandLength] = '\0';
                //String Tokenization
                char *Cmd_Data = strtok(BufferCommand, " ");
                char *args = strtok(NULL, " ");
                char *args1 = strtok(NULL, " ");
                //char *args1 = strtok(NULL, " ");
                if (Cmd_Data != NULL) {
                    if (strcasecmp(Cmd_Data, "SIN") == 0) {
                    	printf("Generate SIN wave\r\n");
                    	sin_frequency = atoi(args);
                    	printf("sin_frequency %d\r\n",sin_frequency);

                    } else if (strcasecmp(Cmd_Data, "SQUARE") == 0) {
                    	printf("Generate SQUARE wave\r\n");
                    	square_frequency = atoi(args);
                    	printf("square_frequency %d\r\n",square_frequency);
                    	duty_cycle  = atoi(args1);
                    	printf("duty_cycle %d\r\n",duty_cycle);
                    	TIM3->CCR2=125;
                    }else {
                        printf("Unknown command(%s)\r\n", Cmd_Data);
                    }
                }

                CommandLength = 0;
                printf("$$ ");
                fflush(stdout);
            } else if (CommandLength < MAX_COMMAND_LEN - 1 && ch >= 32 && ch <= 126) {
                BufferCommand[CommandLength++] = ch;
            }
        }
    }
    printf("\r\n$$ ");
    fflush(stdout);
}



int main(void) {
	Generate_SineWave(sine_wave_440, SINE_TABLE_SIZE_440Hz, SAMPLE_SIZE_440Hz);
	Generate_SineWave(sine_wave_587, SINE_TABLE_SIZE_587Hz, SAMPLE_SIZE_587Hz);
	Generate_SineWave(sine_wave_659, SINE_TABLE_SIZE_659Hz, SAMPLE_SIZE_659Hz);
	Generate_SineWave(sine_wave_880, SINE_TABLE_SIZE_880Hz, SAMPLE_SIZE_880Hz);
    Initialize_UART();
    printf("$$ FUNCTION GENERATOR!\r\n");
    Tim3_init();
   // Initialize_LED();
    command_processor();
    while(1);
}
